<a href="https://colab.research.google.com/github/Nicacio8996/ciencia-de-datos-clases/blob/main/RepasoSemillero_14_10_2026CienciaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#

#Inicio De Ciencia De Datos

In [1]:
print("Hola")

Hola

#Iniciando con dataFrame

In [2]:
import pandas as pd

# Datos para el DataFrame se integran en un diccionario
datos = {
    "Nombre": ["Ana", "Bruno", "Carla", "Diego", "Elena"],
    "Edad": [15, 16, 15, 17, 16],
    "Curso": ["3A", "3B", "3A", "4A", "3B"],
    "Horas de estudio": [4, 2, 6, 1, 5],
    "Nota": [8, 6, 9, 5, 8]
}

# Crear el DataFrame
df = pd.DataFrame(datos)

# Mostrar la tabla
df

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
1  Bruno    16    3B                 2     6
2  Carla    15    3A                 6     9
3  Diego    17    4A                 1     5
4  Elena    16    3B                 5     8

#Cuantas Filas tiene el DataFrame

In [3]:
len(df)

5

#Busca el Valor mas alto de la columna Nota

In [4]:
df['Nota'].max()

9

#Busaca el Vlor Mas Bajo de la  columna nota

In [5]:
df['Nota'].min()

5

#Calcula el promedio de la columna Nota

In [6]:
df["Nota"].mean()

np.float64(7.2)

In [7]:
df['Curso'].value_counts()

Curso
3A    2
3B    2
4A    1
Name: count, dtype: int64

#Calcula el promedio de horas de estudio

In [8]:
df['Horas de estudio' ].mean()

np.float64(3.6)

#Que estudiantes tiene la nota mayor o igual a 8

In [9]:
df[df['Nota'] >= 8]

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
2  Carla    15    3A                 6     9
4  Elena    16    3B                 5     8

#Estudiantes con Nota mayor o igual a 8

In [11]:
# Crear el filtro condicional
filtro_nota = df['Nota'] >= 8

In [12]:
# Aplicar el filtro al DataFrame
estudiantes_destacados = df[filtro_nota]

In [13]:
# Mostrar el resultado
estudiantes_destacados

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
2  Carla    15    3A                 6     9
4  Elena    16    3B                 5     8

# También se puede escribir de forma abreviada y directa en una sola línea:

In [14]:
df[df['Nota'] >= 8]

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
2  Carla    15    3A                 6     9
4  Elena    16    3B                 5     8

# Combinar múltiples condiciones (Operadores lógicos)

#Ejemplo con AND (&): Estudiantes del curso "3A" y que hayan estudiado más de 4 horas:

In [15]:
# Nota: Cada condición individual debe ir obligatoriamente entre paréntesis ()
estudiantes_3a_estudiosos = df[(df['Curso'] == '3A') & (df['Horas de estudio'] > 4)]

estudiantes_3a_estudiosos

  Nombre  Edad Curso  Horas de estudio  Nota
2  Carla    15    3A                 6     9

#Ejemplo con OR (|): Estudiantes que tengan una nota de 9 o cuya edad sea de 17 años:

In [16]:
estudiantes_especiales = df[(df['Nota'] == 9) | (df['Edad'] == 17)]

estudiantes_especiales

  Nombre  Edad Curso  Horas de estudio  Nota
2  Carla    15    3A                 6     9
3  Diego    17    4A                 1     5

#Promedio de notas únicamente de los alumnos del curso 3A

In [17]:
df[df['Curso'] == '3A']['Nota'].mean()

np.float64(8.5)

#DE AQUI EN ADELANTE ES LA CLASE N° 2 DE CIENCIA DE DATOS

In [18]:
df

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
1  Bruno    16    3B                 2     6
2  Carla    15    3A                 6     9
3  Diego    17    4A                 1     5
4  Elena    16    3B                 5     8

# Los estudiantes que estudiaron mas horas optubienron mejores notas

In [20]:
df[['Horas de estudio', 'Nota']]

   Horas de estudio  Nota
0                 4     8
1                 2     6
2                 6     9
3                 1     5
4                 5     8

#Cuantas filas y columnas tiene el DataFrame

In [21]:
df.shape

(5, 5)

#Cuales son los nombres de las columnas

In [22]:
df.columns

Index(['Nombre', 'Edad', 'Curso', 'Horas de estudio', 'Nota'], dtype='object')

#Cuales son las notas registradas

In [23]:
df['Nota']

0    8
1    6
2    9
3    5
4    8
Name: Nota, dtype: int64