#

#Inicio De Ciencia De Datos

In [1]:
print("Hola")

Hola

#Iniciando con dataFrame

In [2]:
import pandas as pd

# Datos para el DataFrame se integran en un diccionario
datos = {
    "Nombre": ["Ana", "Bruno", "Carla", "Diego", "Elena"],
    "Edad": [15, 16, 15, 17, 16],
    "Curso": ["3A", "3B", "3A", "4A", "3B"],
    "Horas de estudio": [4, 2, 6, 1, 5],
    "Nota": [8, 6, 9, 5, 8]
}

# Crear el DataFrame
df = pd.DataFrame(datos)

# Mostrar la tabla
df

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
1  Bruno    16    3B                 2     6
2  Carla    15    3A                 6     9
3  Diego    17    4A                 1     5
4  Elena    16    3B                 5     8

#Cuantas Filas tiene el DataFrame

In [3]:
len(df)

5

#Busca el Valor mas alto de la columna Nota

In [4]:
df['Nota'].max()

9

#Busaca el Vlor Mas Bajo de la  columna nota

In [5]:
df['Nota'].min()

5

#Calcula el promedio de la columna Nota

In [6]:
df["Nota"].mean()

np.float64(7.2)

#Cuenta cuantas vec3s aparece cada curso

In [7]:
df['Curso'].value_counts()

Curso
3A    2
3B    2
4A    1
Name: count, dtype: int64

#Calcula el promedio de horas de estudio

In [8]:
df['Horas de estudio' ].mean()

np.float64(3.6)

#Que estudiantes tiene la nota mayor o igual a 8

In [9]:
df[df['Nota'] >= 8]

  Nombre  Edad Curso  Horas de estudio  Nota
0    Ana    15    3A                 4     8
2  Carla    15    3A                 6     9
4  Elena    16    3B                 5     8